Admin Dashboard about to be ready
sagyMoveo/Epicure-admin pull request #2
Opened 2023-08-28 14:25 UTC by sagyMoveo

2023-08-29 06:24 UTC, nir-boost requested changes

2023-08-29 06:24 UTC, nir-boost commented on src/App.tsx
> +        <Route path='/try' element={<TryComp />} />
1. We want to redirect when a user puts an unknown URL. 

2. we use all the route paths as const :
const ROUTES ={ 
DASHBOARD: '/dashboard',
TRY: '/try'
}

2023-08-29 06:24 UTC, nir-boost commented on src/TryComp.tsx
> +  );
```suggestion
  const { objectToUpdateRedux } = useSelector(
    (state: RootState) => state.collectionsData,
  );
```

2023-08-29 06:24 UTC, nir-boost commented on src/data/utils/emptyObjects/EmptyObjects.ts
> +    return dishes;
already have this const? 
if not make one

2023-08-29 06:24 UTC, nir-boost commented on src/redux/slices/collections.slice.ts
> +  currentCollection: 'chefs',
use Const

2023-08-29 06:24 UTC, nir-boost commented on src/services/api.service.ts
> +    console.log(`${API_BASE_URL}/${collectionName}`);
remove logs

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ModelButton/ModelButton.component.tsx
> +    console.log(`Delete element ${elemId} from collection ${collection}`);
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ModelButton/ModelButton.component.tsx
> +        x
use resources or const

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +      console.log('updatedSelected:', updatedSelected);
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +      console.log({ [fieldName]: updatedIds });
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +            }}
extract style  to style file

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/Table/Table.component.tsx
> +        {/* <span>Create New</span> <img src={addNewIcon} alt='' /> */}
remove comment

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/TagsArray/TagsArray.component.tsx
> +
please delete if nor relevant

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/TagsArray/TagsArray.component.tsx
> +    console.log('add new');
remove logs

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/TagsArray/TagsArray.component.tsx
> +    console.log(tagToAdd);
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/shared/parsers/TableLine.parser.tsx
> +    return 'No restaurants assigned';
looks like use the same text and just the model name change please use it in const and resources for it

2023-08-29 06:24 UTC, nir-boost commented on src/shared/parsers/TableLine.parser.tsx
> +          }
use const

2023-08-29 06:24 UTC, nir-boost commented on src/shared/parsers/TableLine.parser.tsx
> +      />
use const

2023-08-29 06:24 UTC, nir-boost commented on src/shared/parsers/TableLine.parser.tsx
> +    return <img style={{ width: '140px' }} src={cell as string} alt='' />;
extract style  to style file

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/ImageCell/ImageCell.component.tsx
> +      .catch((err) => console.log(err));
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/shared/components/TableLine/TableLine.component.tsx
> +    console.log(
remove log

2023-08-29 06:24 UTC, nir-boost commented on src/services/api.service.ts
> +    console.error('Error updating item:', error);
remove log

2023-08-29 08:26 UTC, sagyMoveo commented on src/App.tsx
> +        <Route path='/try' element={<TryComp />} />
done

2023-08-29 08:27 UTC, sagyMoveo commented on src/TryComp.tsx
> +  );
done

2023-08-29 08:32 UTC, sagyMoveo commented on src/data/utils/emptyObjects/EmptyObjects.ts
> +    return dishes;
done

2023-08-29 08:33 UTC, sagyMoveo commented on src/redux/slices/collections.slice.ts
> +  currentCollection: 'chefs',
done

2023-08-29 09:15 UTC, sagyMoveo commented on src/shared/components/ModelButton/ModelButton.component.tsx
> +    console.log(`Delete element ${elemId} from collection ${collection}`);
Component deleted.

2023-08-29 09:15 UTC, sagyMoveo commented on src/shared/components/ModelButton/ModelButton.component.tsx
> +        x
Component deleted.

2023-08-29 09:18 UTC, sagyMoveo commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +      console.log('updatedSelected:', updatedSelected);
done

2023-08-29 09:19 UTC, sagyMoveo commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +      console.log({ [fieldName]: updatedIds });
done

2023-08-29 09:26 UTC, sagyMoveo commented on src/shared/components/ModelSelectMultiple/ModelSelectMultiple.component.tsx
> +            }}
done

2023-08-29 10:13 UTC, sagyMoveo commented on src/shared/components/TagsArray/TagsArray.component.tsx
> +    console.log('add new');
done

2023-08-29 10:14 UTC, sagyMoveo commented on src/shared/parsers/TableLine.parser.tsx
> +          }
done.

2023-08-29 10:14 UTC, sagyMoveo commented on src/shared/parsers/TableLine.parser.tsx
> +      />
done.

2023-08-29 10:19 UTC, sagyMoveo commented on src/shared/parsers/TableLine.parser.tsx
> +    return <img style={{ width: '140px' }} src={cell as string} alt='' />;
done

2023-08-29 10:19 UTC, sagyMoveo commented on src/shared/components/ImageCell/ImageCell.component.tsx
> +      .catch((err) => console.log(err));
changed to console.error

2023-08-29 10:23 UTC, sagyMoveo commented on src/shared/components/TableLine/TableLine.component.tsx
> +    console.log(
done

2023-08-29 10:28 UTC, sagyMoveo commented on src/services/api.service.ts
> +    console.error('Error updating item:', error);
can i let it stay as console.error?
or its better be off no matter what?

2023-08-30 06:46 UTC, nir-boost approved these changes

2023-08-30 06:48 UTC, merged